from random import randint
import cv2

import albumentations as alb
import matplotlib.pyplot as plt
import numpy as np

from src.augmentation.bbox_manipulation import *
from src.image_manipulation.utils import open_rgb_image
from src.augmentation.perform_augmentation import augmentation_pipeline, just_resize

img = 'sampleB (6)'
imagepath = f'dataset2/images/{img}.jpg' # image that will be tested for augmentation
bboxespath = f'dataset2/labels/{img}.txt' # bboxes file in yolo format
image = open_rgb_image (imagepath)
bboxes = load_bbox_list(bboxespath)

imgs = []
for i in range (9):
    if i == 0:
        transformed = just_resize(image=image, bboxes=bboxes)
    else:
        transformed = augmentation_pipeline(image=image, bboxes=bboxes)

    transformed_image = transformed['image']
    transformed_bboxes = transformed['bboxes']
    imgs.append (transformed_image)
    draw_yolo_bbox (transformed_image, transformed_bboxes)
    #save_bbox_list (f'{i}.txt', transformed_bboxes)

plt.imshow (np.concatenate (
    [
        np.concatenate (imgs[:3], axis=1),
        np.concatenate(imgs[3:6], axis=1),
        np.concatenate(imgs[6:], axis=1)
    ]
))
plt.title ('images generated by random data-augmentation ')
plt.show()